### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by AxelSoler** [emiliazm/recipe-app#13]
## 2 Team members @emiliazm and @AxelSoler 

Hello code reviewer, this is our link to the kanban board for the recipes app project

[Link to the kanban board](https://github.com/users/emiliazm/projects/2/views/1)

**Comment by KDlamini** [comment]
### Hi team @AxelSoler, @emiliazm 🙋‍♀️,  

Excellent work! 💯 
You have done a great job setting up your kanban board. 
Congratulations!!!🎊 🥳 

# Status: Approved ✔️ 

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
